version: '3.5'

services:
  segloader:
    build:
      context: .
    image: quip_segloader
    container_name: quip-segloader
    volumes:
      - ./data:/data
    networks:
      - quip_distro_default

networks:
  quip_distro_default:
   name: quip_distro_default
