version: '3.5'

services:
  segloaderdev:
    build:
      context: .
    image: quip_segloader_dev
    container_name: quip-segloader-dev
    volumes:
      - ./data:/data
    networks:
      - quip_distro_default

networks:
  quip_distro_default:
   name: quip_distro_default
